web:
  image: nginx
  volumes:
   - ./nginx.conf:/etc/nginx/nginx.conf
   - ./dist/:/etc/nginx/html/
  ports:
   - "80:80"
   - "8080:8080"
  environment:
   - NGINX_HOST=cortijodemazas.com
   - NGINX_PORT=80
